// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxsVXNGCTqMCF8F7N5MjzokF3Nbig7v4M',
    appId: '1:932396176333:web:7bac7bda910438e295aa84',
    messagingSenderId: '932396176333',
    projectId: 'getspot01',
    authDomain: 'getspot01.firebaseapp.com',
    storageBucket: 'getspot01.firebasestorage.app',
    measurementId: 'G-DW8K5E419Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv4e7YSOf80uaVDcUy03esDJK0_sduOp8',
    appId: '1:932396176333:android:6a7f6c73b2a9bfda95aa84',
    messagingSenderId: '932396176333',
    projectId: 'getspot01',
    storageBucket: 'getspot01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRq3FA6trnWxams_wPPuHKf8i57iNBkI0',
    appId: '1:932396176333:ios:d450a81c59871df795aa84',
    messagingSenderId: '932396176333',
    projectId: 'getspot01',
    storageBucket: 'getspot01.firebasestorage.app',
    iosClientId: '932396176333-7gc9tuv0jk5egk30tngdapkb0ln2d0qd.apps.googleusercontent.com',
    iosBundleId: 'org.getspot',
  );
}
