# This workflow will deploy your Firebase Functions when a push is made to the main branch
# that includes changes in the 'functions' directory.

name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
  workflow_dispatch:

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GETSPOT01 }}'

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22' # Match the version in package.json

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Install Functions Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./functions

      - name: Build TypeScript
        run: pnpm run build
        working-directory: ./functions

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@5edc2e4fb0c08474ccf6cc71b29f49502aae5401 # v15.28.2
        with:
          args: deploy --only functions --force
        env:
          GCP_SA_KEY: ${{ secrets.GITHUBACTIONSDEPLOY }}
